# Regressão Linear — Água dos Alpes


In [2]:
import pandas as pd

In [6]:
dados = pd.read_csv("/agua_alpes.csv")
dados

,BPt,Pressure
0,194.5,20.79
1,194.3,20.79
2,197.9,22.40
3,198.4,22.67
4,199.4,23.15
5,199.9,23.35
6,200.9,23.89
7,201.1,23.99
8,201.4,24.02
9,201.3,24.01


In [7]:
X = dados[["BPt"]]
y = dados["Pressure"]

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
modelo = LinearRegression()

In [10]:
modelo.fit(X, y)

LinearRegression()

In [11]:
modelo.coef_

array([0.5228924])

In [12]:
modelo.intercept_

np.float64(-81.06372712865588)

In [13]:
temperatura_200 = pd.DataFrame({"BPt": [200]})
modelo.predict(temperatura_200)

array([23.51475303])

In [14]:
temperatura_215 = pd.DataFrame({"BPt": [215]})
modelo.predict(temperatura_215)

array([31.35813904])

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [16]:
y_pred = modelo.predict(X)

In [17]:
mae = mean_absolute_error(y, y_pred)

mae

0.1615749422573339

In [18]:
mse = mean_squared_error(y, y_pred)
mse

0.04783194197896838

In [19]:
r2 = r2_score(y, y_pred)
r2

0.9944281526462317

In [20]:
rmse = mse ** 0.5
rmse

0.21870514849671094

In [21]:
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 0.1615749422573339
MSE: 0.04783194197896838
RMSE: 0.21870514849671094
R²: 0.9944281526462317


In [22]:
pressao_200 = modelo.predict(pd.DataFrame({"BPt": [200]}))[0]
pressao_215 = modelo.predict(pd.DataFrame({"BPt": [215]}))[0]

print("Pressão prevista para 200°F:", pressao_200)
print("Pressão prevista para 215°F:", pressao_215)

Pressão prevista para 200°F: 23.514753028271258
Pressão prevista para 215°F: 31.358139040040797


# Regressão Linear — Livros e Aulas × Notas

In [23]:
notas = pd.read_csv("/notas.csv")
notas

,livros,aulas,notas
0,0,9,45
1,1,15,57
2,0,10,45
3,2,16,51
4,4,10,65
5,4,20,88
6,1,11,44
7,4,20,87
8,3,15,89
9,0,15,59


In [24]:
X = notas[["livros", "aulas"]]
y = notas["notas"]

In [25]:
modelo_notas = LinearRegression()

In [26]:
modelo_notas.fit(X, y)

LinearRegression()

In [27]:
modelo_notas.coef_

array([4.03689261, 1.28347727])

In [28]:
modelo_notas.intercept_

np.float64(37.379185204571236)

In [29]:
aluno1 = pd.DataFrame({"livros": [2], "aulas": [11]})

modelo_notas.predict(aluno1)

array([59.57122045])

In [30]:
aluno2 = pd.DataFrame({"livros": [0], "aulas": [5]})

modelo_notas.predict(aluno2)

array([43.79657158])

In [31]:
aluno3 = pd.DataFrame({"livros": [4], "aulas": [20]})

modelo_notas.predict(aluno3)

array([79.19630114])

In [32]:
aluno4 = pd.DataFrame({"livros": [2], "aulas": [10]})

modelo_notas.predict(aluno4)

array([58.28774317])

In [33]:
aluno5 = pd.DataFrame({"livros": [4], "aulas": [15]})

modelo_notas.predict(aluno5)

array([72.77891477])

In [34]:
y_pred_notas = modelo_notas.predict(X)

In [35]:
mae_notas = mean_absolute_error(y, y_pred_notas)
mae_notas

11.371373549681588

In [36]:
mse_notas = mean_squared_error(y, y_pred_notas)
mse_notas

182.65573824478759

In [37]:
rmse_notas = mse_notas ** 0.5

rmse_notas

13.515018987955125

In [38]:
r2_notas = r2_score(y, y_pred_notas)
r2_notas

0.32871217763931093

In [39]:
print("MAE:", mae_notas)
print("MSE:", mse_notas)
print("RMSE:", rmse_notas)
print("R²:", r2_notas)

MAE: 11.371373549681588
MSE: 182.65573824478759
RMSE: 13.515018987955125
R²: 0.32871217763931093


In [40]:
print("2 livros e 11 aulas:", modelo_notas.predict(pd.DataFrame({"livros": [2], "aulas": [11]}))[0])
print("0 livros e 5 aulas:", modelo_notas.predict(pd.DataFrame({"livros": [0], "aulas": [5]}))[0])
print("4 livros e 20 aulas:", modelo_notas.predict(pd.DataFrame({"livros": [4], "aulas": [20]}))[0])
print("2 livros e 10 aulas:", modelo_notas.predict(pd.DataFrame({"livros": [2], "aulas": [10]}))[0])
print("4 livros e 15 aulas:", modelo_notas.predict(pd.DataFrame({"livros": [4], "aulas": [15]}))[0])

2 livros e 11 aulas: 59.571220448399195
0 livros e 5 aulas: 43.79657157812092
4 livros e 20 aulas: 79.19630114280727
2 livros e 10 aulas: 58.28774317368926
4 livros e 15 aulas: 72.7789147692576


# Classificação — Iris Flower com KNN

In [41]:
from sklearn.datasets import load_iris

In [42]:
iris_X, iris_y = load_iris(return_X_y=True)

In [43]:
iris_X.shape

(150, 4)

In [44]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_X,
    iris_y,
    test_size=0.2,
    random_state=42
)

In [47]:
print("Treinamento:", X_train.shape)
print("Teste:", X_test.shape)

Treinamento: (120, 4)
Teste: (30, 4)


In [48]:
from sklearn.neighbors import KNeighborsClassifier

In [49]:
knn = KNeighborsClassifier()

In [50]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [51]:
y_pred_iris = knn.predict(X_test)

In [52]:
from sklearn.metrics import accuracy_score

In [53]:
acuracia = accuracy_score(y_test, y_pred_iris)
acuracia

1.0

In [54]:
print("Acurácia:", acuracia)
print("Acurácia (%):", acuracia * 100)

Acurácia: 1.0
Acurácia (%): 100.0


In [55]:
from sklearn.metrics import classification_report

In [56]:
print(classification_report(y_test, y_pred_iris))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [57]:
from sklearn.metrics import confusion_matrix

In [58]:
matriz = confusion_matrix(y_test, y_pred_iris)
matriz

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [59]:
iris = load_iris()
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [60]:
print(classification_report(
    y_test,
    y_pred_iris,
    target_names=iris.target_names
))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

